name: clang

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
       - '**'

jobs:
  build:

    runs-on: ubuntu-22.04

    env:
      CC: clang
      CXX: clang++

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt -y install clang make

    - name: Build
      run: |
        make clean
        make

