name: gcc

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
       - '**'

jobs:
  build:

    runs-on: ubuntu-22.04

    env:
      CC: gcc
      CXX: g++

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt -y install gcc make

    - name: Build
      run: |
        make clean
        make

