name: patch

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
       - '**'

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt -y install git

    - name: Clone st
      working-directory: ./ws
      run: |
        git clone https://git.suckless.org/st

    - name: Generate patch
      working-directory: ./ws/st
      run: |
        git remote add -f b https://github.com/wojciechmadry/st.git
        git remote update
        git diff master remotes/b/master > wojciechmadry.patch
        git remote rm b

    - uses: actions/upload-artifact@v3
      with:
        name: wojciechmadry.patch
        path: ./ws/st/wojciechmadry.patch
